ARG BASE_IMAGE
FROM ${BASE_IMAGE}

COPY testng-7.11.0.jar /opt/autoforge/testng/testng-7.11.0.jar
COPY jcommander-1.83.jar /opt/autoforge/testng/jcommander-1.83.jar
COPY slf4j-api-2.0.16.jar /opt/autoforge/testng/slf4j-api-2.0.16.jar
COPY jquery-3.7.1.jar /opt/autoforge/testng/jquery-3.7.1.jar
